//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
[System.Xml.Serialization.XmlRootAttribute("ActivityGoals", Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1", IsNullable=false)]
public partial class ActivityGoals_t {
    
    private ActivityGoal_t[] activityGoalField;
    
    private Extensions_t extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActivityGoal")]
    public ActivityGoal_t[] ActivityGoal {
        get {
            return this.activityGoalField;
        }
        set {
            this.activityGoalField = value;
        }
    }
    
    /// <remarks/>
    public Extensions_t Extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
public partial class ActivityGoal_t {
    
    private string nameField;
    
    private Period_t periodField;
    
    private Extensions_t extensionsField;
    
    private Sport_t sportField;
    
    private Measure_t measureField;
    
    private float targetField;
    
    private float currentField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public Period_t Period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    public Extensions_t Extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Sport_t Sport {
        get {
            return this.sportField;
        }
        set {
            this.sportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public Measure_t Measure {
        get {
            return this.measureField;
        }
        set {
            this.measureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Current {
        get {
            return this.currentField;
        }
        set {
            this.currentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
public partial class Period_t {
    
    private System.DateTime startDateTimeField;
    
    private System.DateTime endDateTimeField;
    
    private bool endDateTimeFieldSpecified;
    
    private RecurrenceCode_t recurrenceField;
    
    private ushort daysPerPeriodField;
    
    public Period_t() {
        this.daysPerPeriodField = ((ushort)(7));
    }
    
    /// <remarks/>
    public System.DateTime StartDateTime {
        get {
            return this.startDateTimeField;
        }
        set {
            this.startDateTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EndDateTime {
        get {
            return this.endDateTimeField;
        }
        set {
            this.endDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndDateTimeSpecified {
        get {
            return this.endDateTimeFieldSpecified;
        }
        set {
            this.endDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RecurrenceCode_t Recurrence {
        get {
            return this.recurrenceField;
        }
        set {
            this.recurrenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(ushort), "7")]
    public ushort DaysPerPeriod {
        get {
            return this.daysPerPeriodField;
        }
        set {
            this.daysPerPeriodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
public enum RecurrenceCode_t {
    
    /// <remarks/>
    Once,
    
    /// <remarks/>
    Daily,
    
    /// <remarks/>
    Weekly,
    
    /// <remarks/>
    Monthly,
    
    /// <remarks/>
    Yearly,
    
    /// <remarks/>
    Custom,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
public partial class Extensions_t {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
public enum Sport_t {
    
    /// <remarks/>
    Running,
    
    /// <remarks/>
    Biking,
    
    /// <remarks/>
    Other,
    
    /// <remarks/>
    All,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityGoals/v1")]
public enum Measure_t {
    
    /// <remarks/>
    DistanceMeters,
    
    /// <remarks/>
    TimeSeconds,
    
    /// <remarks/>
    NumberOfSessions,
    
    /// <remarks/>
    Calories,
}
