//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityExtension/v2")]
[System.Xml.Serialization.XmlRootAttribute("TPX", Namespace="http://www.garmin.com/xmlschemas/ActivityExtension/v2", IsNullable=false)]
public partial class ActivityTrackpointExtension_t {
    
    private double speedField;
    
    private bool speedFieldSpecified;
    
    private byte runCadenceField;
    
    private bool runCadenceFieldSpecified;
    
    private ushort wattsField;
    
    private bool wattsFieldSpecified;
    
    private Extensions_t extensionsField;
    
    private CadenceSensorType_t cadenceSensorField;
    
    private bool cadenceSensorFieldSpecified;
    
    /// <remarks/>
    public double Speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SpeedSpecified {
        get {
            return this.speedFieldSpecified;
        }
        set {
            this.speedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte RunCadence {
        get {
            return this.runCadenceField;
        }
        set {
            this.runCadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RunCadenceSpecified {
        get {
            return this.runCadenceFieldSpecified;
        }
        set {
            this.runCadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort Watts {
        get {
            return this.wattsField;
        }
        set {
            this.wattsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WattsSpecified {
        get {
            return this.wattsFieldSpecified;
        }
        set {
            this.wattsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Extensions_t Extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CadenceSensorType_t CadenceSensor {
        get {
            return this.cadenceSensorField;
        }
        set {
            this.cadenceSensorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CadenceSensorSpecified {
        get {
            return this.cadenceSensorFieldSpecified;
        }
        set {
            this.cadenceSensorFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityExtension/v2")]
public partial class Extensions_t {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityExtension/v2")]
public enum CadenceSensorType_t {
    
    /// <remarks/>
    Footpod,
    
    /// <remarks/>
    Bike,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.garmin.com/xmlschemas/ActivityExtension/v2")]
[System.Xml.Serialization.XmlRootAttribute("LX", Namespace="http://www.garmin.com/xmlschemas/ActivityExtension/v2", IsNullable=false)]
public partial class ActivityLapExtension_t {
    
    private double avgSpeedField;
    
    private bool avgSpeedFieldSpecified;
    
    private byte maxBikeCadenceField;
    
    private bool maxBikeCadenceFieldSpecified;
    
    private byte avgRunCadenceField;
    
    private bool avgRunCadenceFieldSpecified;
    
    private byte maxRunCadenceField;
    
    private bool maxRunCadenceFieldSpecified;
    
    private ushort stepsField;
    
    private bool stepsFieldSpecified;
    
    private ushort avgWattsField;
    
    private bool avgWattsFieldSpecified;
    
    private ushort maxWattsField;
    
    private bool maxWattsFieldSpecified;
    
    private Extensions_t extensionsField;
    
    /// <remarks/>
    public double AvgSpeed {
        get {
            return this.avgSpeedField;
        }
        set {
            this.avgSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AvgSpeedSpecified {
        get {
            return this.avgSpeedFieldSpecified;
        }
        set {
            this.avgSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte MaxBikeCadence {
        get {
            return this.maxBikeCadenceField;
        }
        set {
            this.maxBikeCadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxBikeCadenceSpecified {
        get {
            return this.maxBikeCadenceFieldSpecified;
        }
        set {
            this.maxBikeCadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte AvgRunCadence {
        get {
            return this.avgRunCadenceField;
        }
        set {
            this.avgRunCadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AvgRunCadenceSpecified {
        get {
            return this.avgRunCadenceFieldSpecified;
        }
        set {
            this.avgRunCadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte MaxRunCadence {
        get {
            return this.maxRunCadenceField;
        }
        set {
            this.maxRunCadenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxRunCadenceSpecified {
        get {
            return this.maxRunCadenceFieldSpecified;
        }
        set {
            this.maxRunCadenceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort Steps {
        get {
            return this.stepsField;
        }
        set {
            this.stepsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StepsSpecified {
        get {
            return this.stepsFieldSpecified;
        }
        set {
            this.stepsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort AvgWatts {
        get {
            return this.avgWattsField;
        }
        set {
            this.avgWattsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AvgWattsSpecified {
        get {
            return this.avgWattsFieldSpecified;
        }
        set {
            this.avgWattsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public ushort MaxWatts {
        get {
            return this.maxWattsField;
        }
        set {
            this.maxWattsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MaxWattsSpecified {
        get {
            return this.maxWattsFieldSpecified;
        }
        set {
            this.maxWattsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public Extensions_t Extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}
